version: "3"
volumes:
 certificates:
services:
  mongodb0:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nhfd57hh9qiu0-
    restart: always
  messenger-server:
    build: .
    environment:
      MONGO_URL: "mongodb://root:nhfd57hh9qiu0-@mongodb0:27017/admin"
      ROOT_URL: "http://messenger-server:3000/"
      PORT: 3000
    restart: always
